In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
ya = np.array([0,1,0,0,1,1,0,1]).reshape(8,1)

In [5]:
X.shape, ya.shape

((8, 3), (8, 1))

In [6]:
def sigmoid(P):
    return 1/(1+np.exp(-P))

In [7]:
sigmoid(5), sigmoid(-5), sigmoid(0)

(0.9933071490757153, 0.0066928509242848554, 0.5)

In [9]:
W = np.random.randn(3,1)
for i in range(10):
    yp = sigmoid(np.dot(X,W))
    dw = np.dot(X.T, (yp-ya))
    W  = W-dw
W

array([[ 2.64277252],
       [-4.08056513],
       [ 2.64237439]])

In [11]:
np.round(sigmoid(np.dot(X,W))) # use trained wts

array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.]])

# Regression

In [32]:
X = np.random.randint(0,5,(50,2))
ya = X[:,0]*0.5 - X[:,1]*2 + 2.5

In [33]:
ya = ya.reshape(50,1)
X.shape, ya.shape

((50, 2), (50, 1))

In [37]:
W = np.random.randn(2,1)
b = -1
cost = []
learning_rate=0.001
for i in range(5000):
    yp = np.dot(X,W) + b 
    dw = np.dot(X.T, (yp-ya))
    W  = W-(learning_rate*dw)
    db = np.sum(yp-ya)
    b  = b-(learning_rate*db)
    cost.append(np.sum((yp-ya)**2)/50)

In [39]:
cost[-5:]

[1.3421087795751379e-28,
 1.3421087795751379e-28,
 1.3421087795751379e-28,
 1.3421087795751379e-28,
 1.3421087795751379e-28]

In [40]:
W, b

(array([[ 0.5],
        [-2. ]]),
 2.4999999999999716)